services:
  server:
    build:
      context: .
    volumes:
       - db_data_sqlite:/var/lib/kutt
       - custom:/kutt/custom
    env_file: .env
    environment:
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
      DISALLOW_REGISTRATION: "false"
      OIDC_ENABLED: "true"
      OIDC_ISSUER: http://7f000101.nip.io:8080
      OIDC_CLIENT_ID: mock-client-id
      OIDC_CLIENT_SECRET: some-client-Secret
      OIDC_SCOPE: openid profile email
      OIDC_APP_URL: http://localhost:3000
    ports:
      - 3000:3000
    links:
      - oidc-server-mock:7f000101.nip.io
  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:0.11.0
    ports:
      - 8080:8080
    domainname: 7f000101.nip.io
    environment:
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      CLIENTS_CONFIGURATION_INLINE: |
        [
          {
            "ClientId": "mock-client-id",
            "ClientSecrets": ["some-client-Secret"],
            "Description": "Mock OIDC",
            "AllowedGrantTypes": ["authorization_code"],
            "AllowAccessTokensViaBrowser": true,
            "RedirectUris": ["http://localhost:3000/*"],
            "AllowedScopes": ["openid", "profile", "email"],
            "IdentityTokenLifetime": 3600,
            "AccessTokenLifetime": 3600
          }
        ]
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1",
            "Username":"user01",
            "Password":"pwd",
            "Claims": [
              { "Type": "name", "Value": "User 01", "ValueType": "string" },
              { "Type": "email", "Value": "user01@example.localhost", "ValueType": "string" }
            ],
          },
          {
            "SubjectId":"2",
            "Username":"user02",
            "Password":"pwd",
            "Claims": [
              { "Type": "name", "Value": "User 02", "ValueType": "string" },
              { "Type": "email", "Value": "user02@example.localhost", "ValueType": "string" }
            ],
          }
        ]
volumes:
  db_data_sqlite:
  custom:
